name: Build & Release FlavorLang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created, published] # Trigger workflow on new release creation

jobs:
  build:
    name: Build FlavorLang & VS Code Extension
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (for VS Code extension)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Even versions are designated as stable

      # Step 3: Install dependencies and build VS Code extension
      - name: Build VS Code extension
        working-directory: vscode-extension
        run: |
          npm ci
          npm audit fix --force || true  # Allow audit to fail without breaking the workflow
          npx @vscode/vsce package
          mv *.vsix flavorlang-extension-${{ matrix.os }}.vsix

      # Step 4: Debug the VSIX file
      - name: Debug VSIX file
        run: ls -la vscode-extension/

      # Step 5: Save the renamed VSIX file as an artifact
      - name: Upload VS Code extension package
        uses: actions/upload-artifact@v4
        with:
          name: flavorlang-extension-${{ matrix.os }}
          path: vscode-extension/flavorlang-extension-${{ matrix.os }}.vsix

      # Step 6: Build FlavorLang interpreter
      - name: Build FlavorLang interpreter
        working-directory: src
        run: make
      - name: Rename FlavorLang interpreter
        run: mv src/flavor src/flavorlang-${{ matrix.os }}

      # Step 7: Debug the interpreter file
      - name: Debug Interpreter File
        run: ls -la src/

      # Step 8: Save the interpreter executable as an artifact
      - name: Upload FlavorLang interpreter executable
        uses: actions/upload-artifact@v4
        with:
          name: flavorlang-interpreter-${{ matrix.os }}
          path: src/flavorlang-${{ matrix.os }}

  release:
    name: Attach Built Artifacts to Release
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    # Only run for release events
    if: ${{ github.event_name == 'release' }}

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Debug upload URL
      - name: Debug upload URL
        run: |
          echo "Upload URL: ${{ github.event.release.upload_url }}"

      # Step 3: Download build artifacts
      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: flavorlang-extension-${{ matrix.os }}
          path: vscode-extension

      - name: Download interpreter artifact
        uses: actions/download-artifact@v4
        with:
          name: flavorlang-interpreter-${{ matrix.os }}
          path: flavorlang

      # Step 4: Debug downloaded files
      - name: Debug Downloaded Artifacts
        run: |
          echo "VSIX contents:" && ls -la vscode-extension/
          echo "Interpreter contents:" && ls -la flavorlang/

      # Step 5: Upload VSIX to release
      - name: Upload VSIX to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: vscode-extension/flavorlang-extension-${{ matrix.os }}.vsix
          asset_name: flavorlang-extension-${{ matrix.os }}.vsix
          asset_content_type: application/octet-stream

      # Step 6: Upload interpreter to release
      - name: Upload interpreter to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: flavorlang/flavorlang-${{ matrix.os }}
          asset_name: flavorlang-${{ matrix.os }}
          asset_content_type: application/octet-stream
