name: Build & Release FlavorLang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    name: Build FlavorLang & VS Code Extension
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build VS Code extension
        working-directory: vscode-extension
        run: |
          npm ci
          npm audit fix --force || true
          npx @vscode/vsce package
          mv *.vsix flavorlang-extension-${{ matrix.os }}.vsix

      - name: Build FlavorLang interpreter
        working-directory: src
        run: make

      - name: Rename FlavorLang interpreter
        run: mv src/flavor src/flavorlang-${{ matrix.os }}

      # **New Step: Make Interpreter Executable**
      - name: Make interpreter executable
        run: chmod +x src/flavorlang-${{ matrix.os }}

      # Upload artifacts separately for clarity
      - name: Upload VS Code extension
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension-${{ matrix.os }}
          path: vscode-extension/flavorlang-extension-${{ matrix.os }}.vsix

      - name: Upload interpreter
        uses: actions/upload-artifact@v4
        with:
          name: interpreter-${{ matrix.os }}
          path: src/flavorlang-${{ matrix.os }}

  release:
    name: Attach Artifacts to Release
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      # Debug step to see file structure
      - name: Debug file structure
        run: |
          echo "Contents of artifacts directory:"
          ls -R ./artifacts
          find ./artifacts -type f

      - name: Upload release artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/**/flavorlang-extension-*.vsix
            ./artifacts/**/flavorlang-*-latest
